// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// h5_create_file
SEXP h5_create_file(std::string path);
RcppExport SEXP _chihaya_h5_create_file(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(h5_create_file(path));
    return rcpp_result_gen;
END_RCPP
}
// h5_create_vector
SEXP h5_create_vector(Rcpp::RObject handle, std::string name, Rcpp::List type, Rcpp::RObject len, int compress, Rcpp::RObject chunk_size);
RcppExport SEXP _chihaya_h5_create_vector(SEXP handleSEXP, SEXP nameSEXP, SEXP typeSEXP, SEXP lenSEXP, SEXP compressSEXP, SEXP chunk_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type type(typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::RObject >::type len(lenSEXP);
    Rcpp::traits::input_parameter< int >::type compress(compressSEXP);
    Rcpp::traits::input_parameter< Rcpp::RObject >::type chunk_size(chunk_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(h5_create_vector(handle, name, type, len, compress, chunk_size));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_chihaya_h5_create_file", (DL_FUNC) &_chihaya_h5_create_file, 1},
    {"_chihaya_h5_create_vector", (DL_FUNC) &_chihaya_h5_create_vector, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_chihaya(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
