# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

h5_group_attribute_exists <- function(gptr, aname) {
    .Call('_chihaya_h5_group_attribute_exists', PACKAGE = 'chihaya', gptr, aname)
}

h5_dataset_attribute_exists <- function(dptr, aname) {
    .Call('_chihaya_h5_dataset_attribute_exists', PACKAGE = 'chihaya', dptr, aname)
}

h5_child_exists <- function(gptr, name, report_type) {
    .Call('_chihaya_h5_child_exists', PACKAGE = 'chihaya', gptr, name, report_type)
}

h5_create_dataset_attribute <- function(dptr, aname, raw_type, raw_dim) {
    .Call('_chihaya_h5_create_dataset_attribute', PACKAGE = 'chihaya', dptr, aname, raw_type, raw_dim)
}

h5_create_group_attribute <- function(gptr, aname, raw_type, raw_dim) {
    .Call('_chihaya_h5_create_group_attribute', PACKAGE = 'chihaya', gptr, aname, raw_type, raw_dim)
}

h5_create_dataset <- function(gptr, dname, raw_type, raw_dim, compress, raw_chunks, is_vlen_str) {
    .Call('_chihaya_h5_create_dataset', PACKAGE = 'chihaya', gptr, dname, raw_type, raw_dim, compress, raw_chunks, is_vlen_str)
}

h5_create_file <- function(path) {
    .Call('_chihaya_h5_create_file', PACKAGE = 'chihaya', path)
}

h5_create_group <- function(gptr, gname) {
    .Call('_chihaya_h5_create_group', PACKAGE = 'chihaya', gptr, gname)
}

h5_list_group_attributes <- function(gptr) {
    .Call('_chihaya_h5_list_group_attributes', PACKAGE = 'chihaya', gptr)
}

h5_list_dataset_attributes <- function(dptr) {
    .Call('_chihaya_h5_list_dataset_attributes', PACKAGE = 'chihaya', dptr)
}

h5_list_children <- function(gptr) {
    .Call('_chihaya_h5_list_children', PACKAGE = 'chihaya', gptr)
}

h5_open_group_attribute <- function(gptr, aname) {
    .Call('_chihaya_h5_open_group_attribute', PACKAGE = 'chihaya', gptr, aname)
}

h5_open_dataset_attribute <- function(dptr, aname) {
    .Call('_chihaya_h5_open_dataset_attribute', PACKAGE = 'chihaya', dptr, aname)
}

h5_close_attribute <- function(aptr) {
    .Call('_chihaya_h5_close_attribute', PACKAGE = 'chihaya', aptr)
}

h5_open_dataset <- function(gptr, dname) {
    .Call('_chihaya_h5_open_dataset', PACKAGE = 'chihaya', gptr, dname)
}

h5_close_dataset <- function(dptr) {
    .Call('_chihaya_h5_close_dataset', PACKAGE = 'chihaya', dptr)
}

h5_open_file <- function(path, read_only) {
    .Call('_chihaya_h5_open_file', PACKAGE = 'chihaya', path, read_only)
}

h5_open_group <- function(gptr, gname) {
    .Call('_chihaya_h5_open_group', PACKAGE = 'chihaya', gptr, gname)
}

h5_close_group <- function(gptr) {
    .Call('_chihaya_h5_close_group', PACKAGE = 'chihaya', gptr)
}

h5_read_attribute <- function(aptr) {
    .Call('_chihaya_h5_read_attribute', PACKAGE = 'chihaya', aptr)
}

h5_read_dataset <- function(dptr) {
    .Call('_chihaya_h5_read_dataset', PACKAGE = 'chihaya', dptr)
}

h5_write_attribute <- function(aptr, vec) {
    .Call('_chihaya_h5_write_attribute', PACKAGE = 'chihaya', aptr, vec)
}

h5_write_dataset <- function(dptr, vec) {
    .Call('_chihaya_h5_write_dataset', PACKAGE = 'chihaya', dptr, vec)
}

