# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

h5_create_dataset_attribute <- function(dptr, aname, raw_type, raw_dim) {
    .Call(`_chihaya_h5_create_dataset_attribute`, dptr, aname, raw_type, raw_dim)
}

h5_create_group_attribute <- function(gptr, aname, raw_type, raw_dim) {
    .Call(`_chihaya_h5_create_group_attribute`, gptr, aname, raw_type, raw_dim)
}

h5_create_dataset <- function(gptr, dname, raw_type, raw_dim, compress, raw_chunks) {
    .Call(`_chihaya_h5_create_dataset`, gptr, dname, raw_type, raw_dim, compress, raw_chunks)
}

h5_create_file <- function(path) {
    .Call(`_chihaya_h5_create_file`, path)
}

h5_create_group <- function(gptr, gname) {
    .Call(`_chihaya_h5_create_group`, gptr, gname)
}

h5_open_dataset <- function(gptr, dname) {
    .Call(`_chihaya_h5_open_dataset`, gptr, dname)
}

h5_open_file <- function(path, read_only) {
    .Call(`_chihaya_h5_open_file`, path, read_only)
}

h5_open_group <- function(gptr, gname) {
    .Call(`_chihaya_h5_open_group`, gptr, gname)
}

h5_read_attribute <- function(aptr) {
    .Call(`_chihaya_h5_read_attribute`, aptr)
}

h5_read_dataset <- function(dptr) {
    .Call(`_chihaya_h5_read_dataset`, dptr)
}

h5_write_attribute <- function(aptr, vec) {
    .Call(`_chihaya_h5_write_attribute`, aptr, vec)
}

h5_write_dataset <- function(dptr, vec) {
    .Call(`_chihaya_h5_write_dataset`, dptr, vec)
}

