# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

h5_create_file <- function(path) {
    .Call(`_chihaya_h5_create_file`, path)
}

h5_create_vector <- function(handle, name, type, len, compress, chunk_size) {
    .Call(`_chihaya_h5_create_vector`, handle, name, type, len, compress, chunk_size)
}

